# Generated by Django 3.2.12 on 2022-04-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
