# Generated by Django 3.2.10 on 2022-05-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_factor_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo')),
            ],
            options={
                'verbose_name_plural': 'اطلاعات پایه',
            },
        ),
    ]
