# Generated by Django 3.2.10 on 2022-05-10 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='شماره همراه')),
                ('active_session', models.UUIDField(null=True)),
            ],
            options={
                'verbose_name': 'کارمند ها',
                'verbose_name_plural': 'کارمند ها',
            },
        ),
    ]
