# Generated by Django 3.2.10 on 2022-05-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_key_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='KavenegarSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(max_length=450)),
                ('login_template_name', models.CharField(max_length=50)),
                ('payment_done_template', models.CharField(max_length=50, null=True)),
                ('notification_phone', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'تنظیمات کاوه نگار',
                'verbose_name_plural': 'تنظیمات کاوه نگار',
            },
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.AlterField(
            model_name='profile',
            name='active_session',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
