# Generated by Django 3.2.10 on 2022-05-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20220510_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kavenegarsetting',
            name='notification_phone',
        ),
        migrations.RemoveField(
            model_name='kavenegarsetting',
            name='payment_done_template',
        ),
    ]
