# Generated by Django 3.2.10 on 2022-05-14 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20220510_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='instagram',
            new_name='nickname',
        ),
    ]
