# Generated by Django 3.2.10 on 2022-05-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_rename_instagram_factor_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='mobile',
        ),
    ]
