# Generated by Django 3.2.10 on 2022-05-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20220517_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name_plural': 'تنظیمات'},
        ),
        migrations.AddField(
            model_name='setting',
            name='bank_card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='kart_be_kart',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='online_pay',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
