# Generated by Django 3.2.10 on 2022-05-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20220523_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='online_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='card_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
