# Generated by Django 3.2.10 on 2022-06-12 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_kavenegarsetting_epayreminder_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
